baseURL = 'http://example.org/'
languageCode = 'ko-kr'
defaultContentLanguage = 'ko'
hasCJKLanguage = true
title = 'paperstar blog'
theme = 'ananke'
newContentEditor = "cursor"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
