post_content_classes = "sans-serif"
custom_css = ["special.css"]

[[ananke_socials]]
name = "github"
url = "https://github.com/2paperstar"

[[ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/paperstar"

[[ananke_socials]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/22159750"

[[ananke_socials]]
name = "twitter"
url = "https://twitter.com/2paperstar"

[[ananke_socials]]
name = "facebook"
